name = input("Enter your name: ")
age = int(input("Enter your age: "))
school = input("Enter your school name: ")
college = input("Enter your college name: ")
percentage10 = float(input("Enter your 10th percentage: "))
percentage12 = float(input("Enter your 12th percentage: "))
print("======= Your information =======")
print("Your name:",name)
print("Your age:",age)
print("Your School name:",school)
print("Your College name:",college)
print("Your 10th percentage:",percentage10)
print("Your 12th percentage:",percentage12)